Azure VN peering documentation
tigergraph/cloud-docs pull request #2
Opened 2021-12-15 18:18 UTC by lennessyy

2021-12-15 21:02 UTC, vpoliakov01 requested changes

2021-12-15 21:02 UTC, vpoliakov01 commented on modules/vpc-peering/pages/azure.adoc
> +In the Peered VPC tab, fill in your link:https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-how-to-find-tenan[Azure tenant ID] and your VN ID (Resource ID for your
```suggestion
In the Peered VPC tab, fill in your link:https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-how-to-find-tenant[Azure tenant ID] and your VN ID (Resource ID for your VN).
```

2021-12-16 16:44 UTC, merged

2021-12-17 08:31 UTC, a-m-thomas commented on modules/vpc-peering/pages/azure.adoc
> +This is a guide for setting up a Virtual Network(VN) peering connection between the TigerGraph Cloud VN and another Azure VN.
Space before the first parenthesis

2021-12-17 08:34 UTC, a-m-thomas reviewed
Clear and easy to follow!

2021-12-17 08:34 UTC, a-m-thomas commented on modules/vpc-peering/pages/azure.adoc
> +If connection is successful, you'll see the connection listed under Azure and its status is "Connected".
If the connection is successful, you'll see the connection listed under Azure with its status shown as "Connected".

2021-12-17 17:29 UTC, lennessyy commented on modules/vpc-peering/pages/azure.adoc
> +This is a guide for setting up a Virtual Network(VN) peering connection between the TigerGraph Cloud VN and another Azure VN.
Thanks for spotting! Fixed